version: "3.8"

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack:0.12.11
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs, s3
      #- DEBUG=${DEBUG- }
      #- DATA_DIR=${DATA_DIR- }
      #- PORT_WEB_UI=${PORT_WEB_UI- }
      #- LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      #- KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      #- DOCKER_HOST=unix:///var/run/docker.sock
      #- HOST_TMP_FOLDER=${TMPDIR}
    #volumes:
      #- "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      #- "/var/run/docker.sock:/var/run/docker.sock"
